import type { Metadata } from "next";
// import { Questrial } from "next/font/google";

import gilroy from './fonts'
import "./globals.css";
import Providers from "./providers";
import { Toaster } from 'react-hot-toast';

// const questrial = Questrial({
//   weight: "400",
//   variable: "--font-questrial",
//   subsets: ["latin"],
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroy.variable} antialiased`}
      >
        <Providers>
          <Toaster position="top-right" />
          {children}
        </Providers>
      </body>
    </html>
  );
}
